# Generated by Django 5.0.6 on 2026-05-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SEOLandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('hero_title', models.CharField(max_length=300)),
                ('hero_subtitle', models.TextField(max_length=500)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='seo/heroes/')),
                ('content', models.TextField(help_text='Main body content (Markdown supported)')),
                ('seo_title', models.CharField(max_length=200)),
                ('seo_description', models.TextField(max_length=320)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/')),
                ('schema_type', models.CharField(default='Organization', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SEO Landing Page',
            },
        ),
    ]
